/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i lineparser.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Cuda implementation of Self Organizing Map";

const char *gengetopt_args_info_usage = "Usage: CudaSOM [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --inputfile=STRING        PATH to the input file  (default=`./')",
  "  -x, --nRows=INT               allows to provide the number of rows of the\n                                  neuron matrix  (default=`0')",
  "  -y, --nColumns=INT            allows to provide the number of columns of the\n                                  neuron matrix  (default=`0')",
  "  -s, --initial_learning_rate=DOUBLE\n                                allows to provide the initial learning rate for\n                                  the training process  (default=`-1')",
  "  -f, --final_learning_rate=DOUBLE\n                                allows to provide the final learning rate for\n                                  the training process  (default=`0')",
  "  -n, --iteration=INT           number of times the dataset is presented to the\n                                  SOM  (default=`-1')",
  "  -v, --verbose                 enables debug print  (default=off)",
  "  -d, --debug                   enables advanced debug prints  (default=off)",
  "      --savedistances           saves distances between reads and the final SOM\n                                  in a file called 'distances.out'\n                                  (default=off)",
  "      --saveall                 saves the input and output SOM in a file. It\n                                  also saves distances between reads and the\n                                  final SOM in a file called 'distances.out'\n                                  (default=off)",
  "      --savepath=STRING         PATH to saving folder  (default=`./')",
  "  -r, --radius=INT              allows to choose the initial radius used by the\n                                  updating function  (default=`0')",
  "      --distance=STRING         allows to choose different types of distance\n                                  functions. Use e for euclidean, s for sum of\n                                  sqares, m for manhattan or t for tanimoto\n                                  (possible values=\"e\", \"s\", \"m\", \"t\"\n                                  default=`e')",
  "      --neighbors=STRING        allows to specify the neighbour function used\n                                  in the learning process. Use g for gaussian,\n                                  b for bubble or m for mexican hat  (possible\n                                  values=\"b\", \"g\", \"m\" default=`g')",
  "      --initialization=STRING   allows to specify how the initial weights of\n                                  the SOM are initialized. Use r for random\n                                  initialization or c for picking random\n                                  vectors from the input file  (possible\n                                  values=\"r\", \"c\" default=`c')",
  "      --lattice=STRING          allows to choose what type of lattice is used\n                                  for the SOM representation. Use s for square\n                                  lattice or e for exagonal lattice  (possible\n                                  values=\"s\", \"e\" default=`e')",
  "      --toroidal                allows to choose between planar topology and\n                                  toroidal topology for edges of the SOM\n                                  (default=off)",
  "      --randomize               enables the randomization of the dataset.\n                                  Before presentig the dataset to the SOM(each\n                                  epoch), all entries are shuffled.\n                                  (default=on)",
  "      --exponential=STRING      enables the exponential decay of the learning\n                                  rate and/or the radius. Use l for learning\n                                  rate, r for radius or b for both  (possible\n                                  values=\"n\", \"l\", \"r\", \"b\"\n                                  default=`n')",
  "      --normalizedistance       enables the normalized mean distance. Not\n                                  avaiable if Tanimoto distance is selected\n                                  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


const char *cmdline_parser_distance_values[] = {"e", "s", "m", "t", 0}; /*< Possible values for distance. */
const char *cmdline_parser_neighbors_values[] = {"b", "g", "m", 0}; /*< Possible values for neighbors. */
const char *cmdline_parser_initialization_values[] = {"r", "c", 0}; /*< Possible values for initialization. */
const char *cmdline_parser_lattice_values[] = {"s", "e", 0}; /*< Possible values for lattice. */
const char *cmdline_parser_exponential_values[] = {"n", "l", "r", "b", 0}; /*< Possible values for exponential. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->inputfile_given = 0 ;
  args_info->nRows_given = 0 ;
  args_info->nColumns_given = 0 ;
  args_info->initial_learning_rate_given = 0 ;
  args_info->final_learning_rate_given = 0 ;
  args_info->iteration_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->debug_given = 0 ;
  args_info->savedistances_given = 0 ;
  args_info->saveall_given = 0 ;
  args_info->savepath_given = 0 ;
  args_info->radius_given = 0 ;
  args_info->distance_given = 0 ;
  args_info->neighbors_given = 0 ;
  args_info->initialization_given = 0 ;
  args_info->lattice_given = 0 ;
  args_info->toroidal_given = 0 ;
  args_info->randomize_given = 0 ;
  args_info->exponential_given = 0 ;
  args_info->normalizedistance_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->inputfile_arg = gengetopt_strdup ("./");
  args_info->inputfile_orig = NULL;
  args_info->nRows_arg = 0;
  args_info->nRows_orig = NULL;
  args_info->nColumns_arg = 0;
  args_info->nColumns_orig = NULL;
  args_info->initial_learning_rate_arg = -1;
  args_info->initial_learning_rate_orig = NULL;
  args_info->final_learning_rate_arg = 0;
  args_info->final_learning_rate_orig = NULL;
  args_info->iteration_arg = -1;
  args_info->iteration_orig = NULL;
  args_info->verbose_flag = 0;
  args_info->debug_flag = 0;
  args_info->savedistances_flag = 0;
  args_info->saveall_flag = 0;
  args_info->savepath_arg = gengetopt_strdup ("./");
  args_info->savepath_orig = NULL;
  args_info->radius_arg = 0;
  args_info->radius_orig = NULL;
  args_info->distance_arg = gengetopt_strdup ("e");
  args_info->distance_orig = NULL;
  args_info->neighbors_arg = gengetopt_strdup ("g");
  args_info->neighbors_orig = NULL;
  args_info->initialization_arg = gengetopt_strdup ("c");
  args_info->initialization_orig = NULL;
  args_info->lattice_arg = gengetopt_strdup ("e");
  args_info->lattice_orig = NULL;
  args_info->toroidal_flag = 0;
  args_info->randomize_flag = 1;
  args_info->exponential_arg = gengetopt_strdup ("n");
  args_info->exponential_orig = NULL;
  args_info->normalizedistance_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->inputfile_help = gengetopt_args_info_help[2] ;
  args_info->nRows_help = gengetopt_args_info_help[3] ;
  args_info->nColumns_help = gengetopt_args_info_help[4] ;
  args_info->initial_learning_rate_help = gengetopt_args_info_help[5] ;
  args_info->final_learning_rate_help = gengetopt_args_info_help[6] ;
  args_info->iteration_help = gengetopt_args_info_help[7] ;
  args_info->verbose_help = gengetopt_args_info_help[8] ;
  args_info->debug_help = gengetopt_args_info_help[9] ;
  args_info->savedistances_help = gengetopt_args_info_help[10] ;
  args_info->saveall_help = gengetopt_args_info_help[11] ;
  args_info->savepath_help = gengetopt_args_info_help[12] ;
  args_info->radius_help = gengetopt_args_info_help[13] ;
  args_info->distance_help = gengetopt_args_info_help[14] ;
  args_info->neighbors_help = gengetopt_args_info_help[15] ;
  args_info->initialization_help = gengetopt_args_info_help[16] ;
  args_info->lattice_help = gengetopt_args_info_help[17] ;
  args_info->toroidal_help = gengetopt_args_info_help[18] ;
  args_info->randomize_help = gengetopt_args_info_help[19] ;
  args_info->exponential_help = gengetopt_args_info_help[20] ;
  args_info->normalizedistance_help = gengetopt_args_info_help[21] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->inputfile_arg));
  free_string_field (&(args_info->inputfile_orig));
  free_string_field (&(args_info->nRows_orig));
  free_string_field (&(args_info->nColumns_orig));
  free_string_field (&(args_info->initial_learning_rate_orig));
  free_string_field (&(args_info->final_learning_rate_orig));
  free_string_field (&(args_info->iteration_orig));
  free_string_field (&(args_info->savepath_arg));
  free_string_field (&(args_info->savepath_orig));
  free_string_field (&(args_info->radius_orig));
  free_string_field (&(args_info->distance_arg));
  free_string_field (&(args_info->distance_orig));
  free_string_field (&(args_info->neighbors_arg));
  free_string_field (&(args_info->neighbors_orig));
  free_string_field (&(args_info->initialization_arg));
  free_string_field (&(args_info->initialization_orig));
  free_string_field (&(args_info->lattice_arg));
  free_string_field (&(args_info->lattice_orig));
  free_string_field (&(args_info->exponential_arg));
  free_string_field (&(args_info->exponential_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->inputfile_given)
    write_into_file(outfile, "inputfile", args_info->inputfile_orig, 0);
  if (args_info->nRows_given)
    write_into_file(outfile, "nRows", args_info->nRows_orig, 0);
  if (args_info->nColumns_given)
    write_into_file(outfile, "nColumns", args_info->nColumns_orig, 0);
  if (args_info->initial_learning_rate_given)
    write_into_file(outfile, "initial_learning_rate", args_info->initial_learning_rate_orig, 0);
  if (args_info->final_learning_rate_given)
    write_into_file(outfile, "final_learning_rate", args_info->final_learning_rate_orig, 0);
  if (args_info->iteration_given)
    write_into_file(outfile, "iteration", args_info->iteration_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  if (args_info->savedistances_given)
    write_into_file(outfile, "savedistances", 0, 0 );
  if (args_info->saveall_given)
    write_into_file(outfile, "saveall", 0, 0 );
  if (args_info->savepath_given)
    write_into_file(outfile, "savepath", args_info->savepath_orig, 0);
  if (args_info->radius_given)
    write_into_file(outfile, "radius", args_info->radius_orig, 0);
  if (args_info->distance_given)
    write_into_file(outfile, "distance", args_info->distance_orig, cmdline_parser_distance_values);
  if (args_info->neighbors_given)
    write_into_file(outfile, "neighbors", args_info->neighbors_orig, cmdline_parser_neighbors_values);
  if (args_info->initialization_given)
    write_into_file(outfile, "initialization", args_info->initialization_orig, cmdline_parser_initialization_values);
  if (args_info->lattice_given)
    write_into_file(outfile, "lattice", args_info->lattice_orig, cmdline_parser_lattice_values);
  if (args_info->toroidal_given)
    write_into_file(outfile, "toroidal", 0, 0 );
  if (args_info->randomize_given)
    write_into_file(outfile, "randomize", 0, 0 );
  if (args_info->exponential_given)
    write_into_file(outfile, "exponential", args_info->exponential_orig, cmdline_parser_exponential_values);
  if (args_info->normalizedistance_given)
    write_into_file(outfile, "normalizedistance", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "inputfile",	1, NULL, 'i' },
        { "nRows",	1, NULL, 'x' },
        { "nColumns",	1, NULL, 'y' },
        { "initial_learning_rate",	1, NULL, 's' },
        { "final_learning_rate",	1, NULL, 'f' },
        { "iteration",	1, NULL, 'n' },
        { "verbose",	0, NULL, 'v' },
        { "debug",	0, NULL, 'd' },
        { "savedistances",	0, NULL, 0 },
        { "saveall",	0, NULL, 0 },
        { "savepath",	1, NULL, 0 },
        { "radius",	1, NULL, 'r' },
        { "distance",	1, NULL, 0 },
        { "neighbors",	1, NULL, 0 },
        { "initialization",	1, NULL, 0 },
        { "lattice",	1, NULL, 0 },
        { "toroidal",	0, NULL, 0 },
        { "randomize",	0, NULL, 0 },
        { "exponential",	1, NULL, 0 },
        { "normalizedistance",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:x:y:s:f:n:vdr:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* PATH to the input file.  */
        
        
          if (update_arg( (void *)&(args_info->inputfile_arg), 
               &(args_info->inputfile_orig), &(args_info->inputfile_given),
              &(local_args_info.inputfile_given), optarg, 0, "./", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "inputfile", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* allows to provide the number of rows of the neuron matrix.  */
        
        
          if (update_arg( (void *)&(args_info->nRows_arg), 
               &(args_info->nRows_orig), &(args_info->nRows_given),
              &(local_args_info.nRows_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nRows", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* allows to provide the number of columns of the neuron matrix.  */
        
        
          if (update_arg( (void *)&(args_info->nColumns_arg), 
               &(args_info->nColumns_orig), &(args_info->nColumns_given),
              &(local_args_info.nColumns_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nColumns", 'y',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* allows to provide the initial learning rate for the training process.  */
        
        
          if (update_arg( (void *)&(args_info->initial_learning_rate_arg), 
               &(args_info->initial_learning_rate_orig), &(args_info->initial_learning_rate_given),
              &(local_args_info.initial_learning_rate_given), optarg, 0, "-1", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "initial_learning_rate", 's',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* allows to provide the final learning rate for the training process.  */
        
        
          if (update_arg( (void *)&(args_info->final_learning_rate_arg), 
               &(args_info->final_learning_rate_orig), &(args_info->final_learning_rate_given),
              &(local_args_info.final_learning_rate_given), optarg, 0, "0", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "final_learning_rate", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* number of times the dataset is presented to the SOM.  */
        
        
          if (update_arg( (void *)&(args_info->iteration_arg), 
               &(args_info->iteration_orig), &(args_info->iteration_given),
              &(local_args_info.iteration_given), optarg, 0, "-1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "iteration", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* enables debug print.  */
        
        
          if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* enables advanced debug prints.  */
        
        
          if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* allows to choose the initial radius used by the updating function.  */
        
        
          if (update_arg( (void *)&(args_info->radius_arg), 
               &(args_info->radius_orig), &(args_info->radius_given),
              &(local_args_info.radius_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "radius", 'r',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* saves distances between reads and the final SOM in a file called 'distances.out'.  */
          if (strcmp (long_options[option_index].name, "savedistances") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->savedistances_flag), 0, &(args_info->savedistances_given),
                &(local_args_info.savedistances_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "savedistances", '-',
                additional_error))
              goto failure;
          
          }
          /* saves the input and output SOM in a file. It also saves distances between reads and the final SOM in a file called 'distances.out'.  */
          else if (strcmp (long_options[option_index].name, "saveall") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->saveall_flag), 0, &(args_info->saveall_given),
                &(local_args_info.saveall_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "saveall", '-',
                additional_error))
              goto failure;
          
          }
          /* PATH to saving folder.  */
          else if (strcmp (long_options[option_index].name, "savepath") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->savepath_arg), 
                 &(args_info->savepath_orig), &(args_info->savepath_given),
                &(local_args_info.savepath_given), optarg, 0, "./", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "savepath", '-',
                additional_error))
              goto failure;
          
          }
          /* allows to choose different types of distance functions. Use e for euclidean, s for sum of sqares, m for manhattan or t for tanimoto.  */
          else if (strcmp (long_options[option_index].name, "distance") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->distance_arg), 
                 &(args_info->distance_orig), &(args_info->distance_given),
                &(local_args_info.distance_given), optarg, cmdline_parser_distance_values, "e", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "distance", '-',
                additional_error))
              goto failure;
          
          }
          /* allows to specify the neighbour function used in the learning process. Use g for gaussian, b for bubble or m for mexican hat.  */
          else if (strcmp (long_options[option_index].name, "neighbors") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->neighbors_arg), 
                 &(args_info->neighbors_orig), &(args_info->neighbors_given),
                &(local_args_info.neighbors_given), optarg, cmdline_parser_neighbors_values, "g", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "neighbors", '-',
                additional_error))
              goto failure;
          
          }
          /* allows to specify how the initial weights of the SOM are initialized. Use r for random initialization or c for picking random vectors from the input file.  */
          else if (strcmp (long_options[option_index].name, "initialization") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->initialization_arg), 
                 &(args_info->initialization_orig), &(args_info->initialization_given),
                &(local_args_info.initialization_given), optarg, cmdline_parser_initialization_values, "c", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "initialization", '-',
                additional_error))
              goto failure;
          
          }
          /* allows to choose what type of lattice is used for the SOM representation. Use s for square lattice or e for exagonal lattice.  */
          else if (strcmp (long_options[option_index].name, "lattice") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lattice_arg), 
                 &(args_info->lattice_orig), &(args_info->lattice_given),
                &(local_args_info.lattice_given), optarg, cmdline_parser_lattice_values, "e", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "lattice", '-',
                additional_error))
              goto failure;
          
          }
          /* allows to choose between planar topology and toroidal topology for edges of the SOM.  */
          else if (strcmp (long_options[option_index].name, "toroidal") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->toroidal_flag), 0, &(args_info->toroidal_given),
                &(local_args_info.toroidal_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "toroidal", '-',
                additional_error))
              goto failure;
          
          }
          /* enables the randomization of the dataset. Before presentig the dataset to the SOM(each epoch), all entries are shuffled..  */
          else if (strcmp (long_options[option_index].name, "randomize") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->randomize_flag), 0, &(args_info->randomize_given),
                &(local_args_info.randomize_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "randomize", '-',
                additional_error))
              goto failure;
          
          }
          /* enables the exponential decay of the learning rate and/or the radius. Use l for learning rate, r for radius or b for both.  */
          else if (strcmp (long_options[option_index].name, "exponential") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->exponential_arg), 
                 &(args_info->exponential_orig), &(args_info->exponential_given),
                &(local_args_info.exponential_given), optarg, cmdline_parser_exponential_values, "n", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "exponential", '-',
                additional_error))
              goto failure;
          
          }
          /* enables the normalized mean distance. Not avaiable if Tanimoto distance is selected.  */
          else if (strcmp (long_options[option_index].name, "normalizedistance") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->normalizedistance_flag), 0, &(args_info->normalizedistance_given),
                &(local_args_info.normalizedistance_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "normalizedistance", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
